# Generated by Django 4.2.5 on 2023-10-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('comment', models.TextField()),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='api.course')),
            ],
        ),
    ]
