# Generated by Django 4.2.5 on 2023-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.CharField(default='pass', max_length=10),
        ),
    ]
