# Generated by Django 4.2.5 on 2023-11-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_review_difficulty_review_workload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cdesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='professor',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
