# Generated by Django 4.2.5 on 2023-11-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tag_value_alter_course_cdesc_alter_review_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='api.tag'),
        ),
    ]
